# Kitty Configuration

# Include the Tokyo Night Storm theme
include tokyonight_storm.conf

# Add any additional preferences below
font_family      Fira Code
font_size        12.0
window_padding_width 4

# Transparency
background_opacity 0.85
