server_url = "http://127.0.0.1:8188"
output_dir = "outputs"
workflows_dir = "workflows"
default_output_name = "ComfyUI"
default_width = 768
default_height = 768
default_steps = 28
[standard_workflows]
txt2img = ""
img2img = ""
canny2img = ""
depth2img = ""
img2vid = ""
txt2vid = ""
txt2img_lora = ""
img2img_inpainting = ""
rmb = ""
